### ISSUE TITLE
gerrit.py:42-44: Найти на сервере (self.remote_ids)...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/manabot#16]
The puzzle `13-2f0c6e17` (from #13) in [`tb/sources/gerrit.py`](https://github.com/DronMDF/manabot/blob/master/tb/sources/gerrit.py) (lines 42-44) has to be resolved: "Найти на сервере (self.remote_ids) что-то такое, чего нет в списке контролируемых. (self.controlled_ids) И на эти ревью создать Action"

The puzzle was created by Andrey Valyaev on 30-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Для тестов можно использовать публичные сервера..
Типа этот:
https://dev.vaadin.com/review/
Он пускает анонимно.

**Comment by 0pdd** [comment]
The puzzle `13-2f0c6e17` has disappeared from the source code, that's why I closed this issue.
