### ISSUE TITLE
setup.py:90-92: Тесты считаются странно, удалил два...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/manabot#73]
The puzzle `71-ba973616` from #71 has to be resolved:

https://github.com/DronMDF/manabot/blob/e13badb2e2c3a59aa4646e0f8d484576df5603bc/setup.py#L90-L92

The puzzle was created by Andrey Valyaev on 05-Jan-18. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Эту надо закрывать...

**Comment by 0pdd** [comment]
The puzzle `71-ba973616` has disappeared from the source code, that's why I closed this issue.
